name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set lowercase REPO name
      - name: Downcase repository name
        run: |
          echo "REPO_OWNER=$(echo ${GITHUB_REPOSITORY_OWNER,,})" >> $GITHUB_ENV
          echo "REPO_NAME=$(basename ${GITHUB_REPOSITORY,,})" >> $GITHUB_ENV

      # Step 3: Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest
            ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:${{ github.sha }}
